name: Release

on:
  push:
    tags:
      - 'v*'

jobs:
  release:
    name: Build & Release
    runs-on: ${{ matrix.os }}
    permissions:
      contents: write # Required for uploading to Releases
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '22'
          cache: 'npm'

      - name: Install dependencies on Linux
        if: matrix.os == 'ubuntu-latest'
        run: sudo apt-get update && sudo apt-get install -y xvfb xauth libgtk-3-0 libnss3 libasound2t64 libxtst6

      - name: Install dependencies
        run: npm ci

      # Build and Publish using electron-builder
      # It will detect the tag and GitHub context automatically
      - name: Publish to GitHub Release
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: npm run publish:gh
